### ISSUE TITLE
除了电影其他视频都是5分钟

### ISSUE THREAD

**Issue by ws115** [fuzhuo/youku_tvos#1]
如题

**Comment by fuzhuo** [comment]
我这边似乎可以的。。。
偶尔会更新程序服务端代码，需要杀掉应用重新打开。重新打开一下看看呢。
另外标记为VIP的视频都有五分钟限制，估计有些视频标记有错误

**Comment by ws115** [comment]
比如任意依恋

**Comment by fuzhuo** [comment]
好像部分非VIP的也确实会只有五分钟时间，我查看一下

**Comment by fuzhuo** [comment]
换了个视频链接解析。。杀掉重启再试试

**Comment by ws115** [comment]
还是一样

**Comment by fuzhuo** [comment]
我这边现在没问题了。。
另外，为方便维护和更新，把几个app合并了一下，以后用下面这个吧。
https://github.com/fuzhuo/LazyCat

**Comment by ws115** [comment]
谢谢，新的里面可以了
